"""Init new DB schema on new PC

Revision ID: 9b15ba822079
Revises: 3dd753a9764e
Create Date: 2025-07-13 12:10:55.639624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b15ba822079'
down_revision: Union[str, Sequence[str], None] = '3dd753a9764e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.add_column('users', sa.Column('email', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.create_table('post',
    sa.Column('post_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('length(content) > 0', name=op.f('chk_length_content')),
    sa.CheckConstraint('length(title::text) > 0', name=op.f('chk_length_title')),
    sa.PrimaryKeyConstraint('post_id', name=op.f('post_pkey'))
    )
    # ### end Alembic commands ###
