"""User.static_token

Revision ID: af95ef832bb6
Revises: 527bf30549fa
Create Date: 2025-07-16 14:23:44.922494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af95ef832bb6'
down_revision: Union[str, Sequence[str], None] = '527bf30549fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('static_token', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'users', ['static_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'static_token')
    # ### end Alembic commands ###
