"""Initial migration

Revision ID: f3d60a9cb63a
Revises: 
Create Date: 2025-07-11 14:20:41.997512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d60a9cb63a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('post_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('length(content) > 0', name=op.f('chk_length_content')),
    sa.CheckConstraint('length(title::text) > 0', name=op.f('chk_length_title')),
    sa.PrimaryKeyConstraint('post_id', name=op.f('post_pkey'))
    )
    # ### end Alembic commands ###
