"""new device

Revision ID: fdcb2c7fc116
Revises: af95ef832bb6
Create Date: 2025-07-18 15:24:28.157045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdcb2c7fc116'
down_revision: Union[str, Sequence[str], None] = 'af95ef832bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('static_token', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'users', ['static_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'static_token')
    # ### end Alembic commands ###
