version: '3s'

services:
  web:
    build: .
    depends_on:
      - db
    enviroment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_DB_USER}@${POSTGRES_DB_HOST}:5433/${POSTGRES_DB_NAME}
    ports:
      - "80:80"

  db:
    image: postgres-15-alpine
    volumes:
      - postgres-data: /var/lib/postgresql/data/
    expose:
      - 5433
    enviroment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
